on:
  push:
     branches:
       - master

name: deployblog

jobs:
  blogdown:
    name: Render-Blog
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: blogdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         name: public
         path: ../public
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          EMAIL: ${{ secrets.EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_DIR: public/
